"""
HAS gRPC Service Definitions (Python Mock)

This module provides Python-native gRPC service stub and servicer classes
for development without protoc.

For production, generate from has.proto.
"""

import logging
from typing import Any, Optional

from . import has_pb2

logger = logging.getLogger(__name__)


class HEAdapterServiceStub:
    """
    Client stub for HE Adapter Service.

    In production, this is generated by grpc_tools.protoc.
    This mock implementation allows development without gRPC installed.
    """

    def __init__(self, channel: Any):
        """
        Initialize stub with gRPC channel.

        Args:
            channel: gRPC channel (or mock)
        """
        self._channel = channel

    def LoadAdapter(
        self,
        request: has_pb2.LoadAdapterRequest,
        timeout: Optional[float] = None,
        metadata: Optional[Any] = None,
    ) -> has_pb2.LoadAdapterResponse:
        """Load a LoRA adapter."""
        # Mock implementation
        return has_pb2.LoadAdapterResponse(
            success=True,
            num_layers=32,
            loaded_layers=list(range(32)),
        )

    def UnloadAdapter(
        self,
        request: has_pb2.UnloadAdapterRequest,
        timeout: Optional[float] = None,
        metadata: Optional[Any] = None,
    ) -> has_pb2.UnloadAdapterResponse:
        """Unload a LoRA adapter."""
        return has_pb2.UnloadAdapterResponse(success=True)

    def GetAdapterInfo(
        self,
        request: has_pb2.GetAdapterInfoRequest,
        timeout: Optional[float] = None,
        metadata: Optional[Any] = None,
    ) -> has_pb2.GetAdapterInfoResponse:
        """Get adapter information."""
        return has_pb2.GetAdapterInfoResponse(success=True)

    def PrepareRequest(
        self,
        request: has_pb2.PrepareRequestRequest,
        timeout: Optional[float] = None,
        metadata: Optional[Any] = None,
    ) -> has_pb2.PrepareRequestResponse:
        """Prepare HE context for a request."""
        return has_pb2.PrepareRequestResponse(success=True)

    def ReleaseRequest(
        self,
        request: has_pb2.ReleaseRequestRequest,
        timeout: Optional[float] = None,
        metadata: Optional[Any] = None,
    ) -> has_pb2.ReleaseRequestResponse:
        """Release HE context."""
        return has_pb2.ReleaseRequestResponse(success=True)

    def ApplyTokenStep(
        self,
        request: has_pb2.ApplyTokenStepRequest,
        timeout: Optional[float] = None,
        metadata: Optional[Any] = None,
    ) -> has_pb2.ApplyTokenStepResponse:
        """Apply HE-LoRA delta for a token step."""
        return has_pb2.ApplyTokenStepResponse(
            success=True,
            has_delta=True,
        )

    def ApplyBatchedTokenStep(
        self,
        request: has_pb2.ApplyBatchedTokenStepRequest,
        timeout: Optional[float] = None,
        metadata: Optional[Any] = None,
    ) -> has_pb2.ApplyBatchedTokenStepResponse:
        """Apply batched HE-LoRA deltas."""
        return has_pb2.ApplyBatchedTokenStepResponse(success=True)

    def HealthCheck(
        self,
        request: has_pb2.HealthCheckRequest,
        timeout: Optional[float] = None,
        metadata: Optional[Any] = None,
    ) -> has_pb2.HealthCheckResponse:
        """Health check."""
        return has_pb2.HealthCheckResponse(healthy=True)

    def GetStatus(
        self,
        request: has_pb2.GetStatusRequest,
        timeout: Optional[float] = None,
        metadata: Optional[Any] = None,
    ) -> has_pb2.GetStatusResponse:
        """Get service status."""
        return has_pb2.GetStatusResponse(healthy=True)

    def GetTelemetry(
        self,
        request: has_pb2.GetTelemetryRequest,
        timeout: Optional[float] = None,
        metadata: Optional[Any] = None,
    ) -> has_pb2.GetTelemetryResponse:
        """Get telemetry data."""
        return has_pb2.GetTelemetryResponse(success=True)


class HEAdapterServiceServicer:
    """
    Server-side servicer for HE Adapter Service.

    Subclass this and implement methods to create the server.
    """

    def LoadAdapter(
        self,
        request: has_pb2.LoadAdapterRequest,
        context: Any,
    ) -> has_pb2.LoadAdapterResponse:
        """Load a LoRA adapter."""
        context.set_code(NotImplementedError)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UnloadAdapter(
        self,
        request: has_pb2.UnloadAdapterRequest,
        context: Any,
    ) -> has_pb2.UnloadAdapterResponse:
        """Unload a LoRA adapter."""
        context.set_code(NotImplementedError)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetAdapterInfo(
        self,
        request: has_pb2.GetAdapterInfoRequest,
        context: Any,
    ) -> has_pb2.GetAdapterInfoResponse:
        """Get adapter information."""
        context.set_code(NotImplementedError)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PrepareRequest(
        self,
        request: has_pb2.PrepareRequestRequest,
        context: Any,
    ) -> has_pb2.PrepareRequestResponse:
        """Prepare HE context for a request."""
        context.set_code(NotImplementedError)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReleaseRequest(
        self,
        request: has_pb2.ReleaseRequestRequest,
        context: Any,
    ) -> has_pb2.ReleaseRequestResponse:
        """Release HE context."""
        context.set_code(NotImplementedError)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ApplyTokenStep(
        self,
        request: has_pb2.ApplyTokenStepRequest,
        context: Any,
    ) -> has_pb2.ApplyTokenStepResponse:
        """Apply HE-LoRA delta for a token step."""
        context.set_code(NotImplementedError)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ApplyBatchedTokenStep(
        self,
        request: has_pb2.ApplyBatchedTokenStepRequest,
        context: Any,
    ) -> has_pb2.ApplyBatchedTokenStepResponse:
        """Apply batched HE-LoRA deltas."""
        context.set_code(NotImplementedError)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(
        self,
        request: has_pb2.HealthCheckRequest,
        context: Any,
    ) -> has_pb2.HealthCheckResponse:
        """Health check."""
        return has_pb2.HealthCheckResponse(healthy=True, message="OK")

    def GetStatus(
        self,
        request: has_pb2.GetStatusRequest,
        context: Any,
    ) -> has_pb2.GetStatusResponse:
        """Get service status."""
        context.set_code(NotImplementedError)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTelemetry(
        self,
        request: has_pb2.GetTelemetryRequest,
        context: Any,
    ) -> has_pb2.GetTelemetryResponse:
        """Get telemetry data."""
        context.set_code(NotImplementedError)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_HEAdapterServiceServicer_to_server(servicer: HEAdapterServiceServicer, server: Any) -> None:
    """
    Add HEAdapterServiceServicer to a gRPC server.

    Args:
        servicer: Service implementation
        server: gRPC server instance
    """
    try:
        import grpc

        rpc_method_handlers = {
            'LoadAdapter': grpc.unary_unary_rpc_method_handler(
                servicer.LoadAdapter,
            ),
            'UnloadAdapter': grpc.unary_unary_rpc_method_handler(
                servicer.UnloadAdapter,
            ),
            'GetAdapterInfo': grpc.unary_unary_rpc_method_handler(
                servicer.GetAdapterInfo,
            ),
            'PrepareRequest': grpc.unary_unary_rpc_method_handler(
                servicer.PrepareRequest,
            ),
            'ReleaseRequest': grpc.unary_unary_rpc_method_handler(
                servicer.ReleaseRequest,
            ),
            'ApplyTokenStep': grpc.unary_unary_rpc_method_handler(
                servicer.ApplyTokenStep,
            ),
            'ApplyBatchedTokenStep': grpc.unary_unary_rpc_method_handler(
                servicer.ApplyBatchedTokenStep,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                servicer.HealthCheck,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                servicer.GetStatus,
            ),
            'GetTelemetry': grpc.unary_unary_rpc_method_handler(
                servicer.GetTelemetry,
            ),
        }
        generic_handler = grpc.method_handlers_generic_handler(
            'helora.HEAdapterService', rpc_method_handlers
        )
        server.add_generic_rpc_handlers((generic_handler,))

    except ImportError:
        logger.warning("gRPC not available, server registration skipped")
