# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from he_lora_microkernel.services.proto import has_pb2 as he__lora__microkernel_dot_services_dot_proto_dot_has__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in he_lora_microkernel/services/proto/has_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HEAdapterServiceStub(object):
    """============================================================================
    SERVICE DEFINITION
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadAdapter = channel.unary_unary(
                '/helora.HEAdapterService/LoadAdapter',
                request_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.LoadAdapterRequest.SerializeToString,
                response_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.LoadAdapterResponse.FromString,
                _registered_method=True)
        self.UnloadAdapter = channel.unary_unary(
                '/helora.HEAdapterService/UnloadAdapter',
                request_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.UnloadAdapterRequest.SerializeToString,
                response_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.UnloadAdapterResponse.FromString,
                _registered_method=True)
        self.GetAdapterInfo = channel.unary_unary(
                '/helora.HEAdapterService/GetAdapterInfo',
                request_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.GetAdapterInfoRequest.SerializeToString,
                response_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.GetAdapterInfoResponse.FromString,
                _registered_method=True)
        self.PrepareRequest = channel.unary_unary(
                '/helora.HEAdapterService/PrepareRequest',
                request_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.PrepareRequestRequest.SerializeToString,
                response_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.PrepareRequestResponse.FromString,
                _registered_method=True)
        self.ReleaseRequest = channel.unary_unary(
                '/helora.HEAdapterService/ReleaseRequest',
                request_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.ReleaseRequestRequest.SerializeToString,
                response_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.ReleaseRequestResponse.FromString,
                _registered_method=True)
        self.ApplyTokenStep = channel.unary_unary(
                '/helora.HEAdapterService/ApplyTokenStep',
                request_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.ApplyTokenStepRequest.SerializeToString,
                response_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.ApplyTokenStepResponse.FromString,
                _registered_method=True)
        self.ApplyBatchedTokenStep = channel.unary_unary(
                '/helora.HEAdapterService/ApplyBatchedTokenStep',
                request_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.ApplyBatchedTokenStepRequest.SerializeToString,
                response_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.ApplyBatchedTokenStepResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/helora.HEAdapterService/HealthCheck',
                request_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/helora.HEAdapterService/GetStatus',
                request_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.GetTelemetry = channel.unary_unary(
                '/helora.HEAdapterService/GetTelemetry',
                request_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.GetTelemetryRequest.SerializeToString,
                response_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.GetTelemetryResponse.FromString,
                _registered_method=True)


class HEAdapterServiceServicer(object):
    """============================================================================
    SERVICE DEFINITION
    ============================================================================

    """

    def LoadAdapter(self, request, context):
        """Adapter management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadAdapter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAdapterInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareRequest(self, request, context):
        """Request lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyTokenStep(self, request, context):
        """Token processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyBatchedTokenStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health and status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTelemetry(self, request, context):
        """Telemetry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HEAdapterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadAdapter': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadAdapter,
                    request_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.LoadAdapterRequest.FromString,
                    response_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.LoadAdapterResponse.SerializeToString,
            ),
            'UnloadAdapter': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadAdapter,
                    request_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.UnloadAdapterRequest.FromString,
                    response_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.UnloadAdapterResponse.SerializeToString,
            ),
            'GetAdapterInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdapterInfo,
                    request_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.GetAdapterInfoRequest.FromString,
                    response_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.GetAdapterInfoResponse.SerializeToString,
            ),
            'PrepareRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareRequest,
                    request_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.PrepareRequestRequest.FromString,
                    response_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.PrepareRequestResponse.SerializeToString,
            ),
            'ReleaseRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseRequest,
                    request_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.ReleaseRequestRequest.FromString,
                    response_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.ReleaseRequestResponse.SerializeToString,
            ),
            'ApplyTokenStep': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyTokenStep,
                    request_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.ApplyTokenStepRequest.FromString,
                    response_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.ApplyTokenStepResponse.SerializeToString,
            ),
            'ApplyBatchedTokenStep': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyBatchedTokenStep,
                    request_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.ApplyBatchedTokenStepRequest.FromString,
                    response_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.ApplyBatchedTokenStepResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.HealthCheckRequest.FromString,
                    response_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.GetStatusRequest.FromString,
                    response_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.GetStatusResponse.SerializeToString,
            ),
            'GetTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTelemetry,
                    request_deserializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.GetTelemetryRequest.FromString,
                    response_serializer=he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.GetTelemetryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helora.HEAdapterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('helora.HEAdapterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HEAdapterService(object):
    """============================================================================
    SERVICE DEFINITION
    ============================================================================

    """

    @staticmethod
    def LoadAdapter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helora.HEAdapterService/LoadAdapter',
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.LoadAdapterRequest.SerializeToString,
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.LoadAdapterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadAdapter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helora.HEAdapterService/UnloadAdapter',
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.UnloadAdapterRequest.SerializeToString,
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.UnloadAdapterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAdapterInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helora.HEAdapterService/GetAdapterInfo',
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.GetAdapterInfoRequest.SerializeToString,
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.GetAdapterInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helora.HEAdapterService/PrepareRequest',
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.PrepareRequestRequest.SerializeToString,
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.PrepareRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helora.HEAdapterService/ReleaseRequest',
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.ReleaseRequestRequest.SerializeToString,
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.ReleaseRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyTokenStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helora.HEAdapterService/ApplyTokenStep',
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.ApplyTokenStepRequest.SerializeToString,
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.ApplyTokenStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyBatchedTokenStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helora.HEAdapterService/ApplyBatchedTokenStep',
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.ApplyBatchedTokenStepRequest.SerializeToString,
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.ApplyBatchedTokenStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helora.HEAdapterService/HealthCheck',
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.HealthCheckRequest.SerializeToString,
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helora.HEAdapterService/GetStatus',
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.GetStatusRequest.SerializeToString,
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helora.HEAdapterService/GetTelemetry',
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.GetTelemetryRequest.SerializeToString,
            he__lora__microkernel_dot_services_dot_proto_dot_has__pb2.GetTelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
